## Data

In [1]:
import pandas as pd

In [2]:
df= pd.read_csv(r'C:\Users\VEDANT\ApnaCollege Course\IMDB Dataset.csv')

In [3]:
df.shape

(50000, 2)

In [4]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [5]:
df.drop_duplicates(inplace=True)

In [6]:
df.shape

(49582, 2)

In [7]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

## Preprocessing

#### 1. convert to lowercase

In [8]:
df["review"]= df["review"].str.lower()

#### 2. remove urls, html, punctuation, stopwords

In [9]:
import re
#sample= "abc is the word, abc"       -> re function is used to replace the word in the string
#new= re.sub("abc", "xyz", sample)

In [10]:
def remove_urls(text):
    # Handle None values by returning empty string
    if text is None:
        return ""
    text= re.sub(r"http\S+", "", text)
    return text

df["review"] = df["review"].apply(remove_urls)

In [11]:
def remove_punctuations(text):
    text= re.sub(r"[^A-Za-z0-9\s]", "", text)
    return text
df["review"] = df["review"].apply(remove_punctuations)

In [12]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [13]:
def remove_HtmlTags(text):
    text= re.sub(r"<.*?>", "", text)
    return text
df["review"]= df["review"].apply(remove_HtmlTags)

In [14]:
import nltk

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\VEDANT\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\VEDANT\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\VEDANT\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [15]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [16]:
#EG: sample= "This is a sample sentence"
#tokens= word_tokenize(sample) -> ['This', 'is', 'a', '

In [17]:
def remove_stopwords(text):
    tokens= word_tokenize(text)
    stop_words= stopwords.words("english")
    for word in tokens:
        if word in stop_words:
            text= text.replace(word, "")
    return text
df["review"]= df["review"].apply(remove_stopwords)

In [18]:
df.head()

                                              review sentiment
0  e    revewers  nted   wtchg  1 oz epode ll  ho...  positive
1   wderful ltle producti br br  filming techniqu...  positive
2   thought ths   wderful wy  spend tme   o hot s...  positive
3  bsclly res  fmly   lttle boy jke thks res  zom...  negative
4  petter mtte love   time  mey   vully stunng fi...  positive

#### 4. stemming

In [19]:
#running -> run
#played -> play
#stemming is the process of reducing a word to its root form. It is a simple rule

In [20]:
from nltk.stem import PorterStemmer

In [21]:
def stemming(text):
    ps= PorterStemmer()
    stemmed_words= []
    tokens= word_tokenize(text)
    for token in tokens:
        stemmed_token= ps.stem(token)
        stemmed_words.append(stemmed_token)
    return " ".join(stemmed_words)
df["review"]= df["review"].apply(stemming)

In [22]:
df.head()

                                              review sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...  positive
1  wder ltle producti br br film techniqu unssum ...  positive
2  thought th wder wy spend tme o hot summer week...  positive
3  bsclli re fmli lttle boy jke thk re zomb close...  negative
4  petter mtte love time mey vulli stunng film wt...  positive

#### 5. encoding sentiments

In [23]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
df["sentiment"]= le.fit_transform(df["sentiment"])

In [24]:
y= df["sentiment"]

In [25]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int32

#### 8. vectorization->TF-IDF

In [26]:
df.head()

                                              review  sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...          1
1  wder ltle producti br br film techniqu unssum ...          1
2  thought th wder wy spend tme o hot summer week...          1
3  bsclli re fmli lttle boy jke thk re zomb close...          0
4  petter mtte love time mey vulli stunng film wt...          1

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf= Tfidf= TfidfVectorizer(max_features= 5000)
X= tf.fit_transform(df["review"])

In [28]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4057169 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3538)	0.05515484681268887
  (0, 2869)	0.09361182809242374
  (0, 4940)	0.11467310366614668
  (0, 3003)	0.47200539890110405
  (0, 1275)	0.1357698919196183
  (0, 2289)	0.049500237517476293
  (0, 1933)	0.0791260308382
  (0, 3550)	0.0963974330192639
  (0, 1362)	0.06162489377343992
  (0, 1963)	0.061560444992697486
  (0, 218)	0.08588920995304898
  (0, 1620)	0.0738170550485134
  (0, 4368)	0.041994187696759305
  (0, 4170)	0.17799685402440263
  (0, 3692)	0.033532198172897175
  (0, 4737)	0.26798942924092045
  (0, 3804)	0.04427609784380831
  (0, 4769)	0.05877405881441711
  (0, 1739)	0.037520883911174724
  (0, 4496)	0.07614066339174266
  (0, 3856)	0.17537900435282314
  (0, 1630)	0.06142445471882175
  (0, 1862)	0.07433134577032253
  (0, 3329)	0.06406818508428483
  (0, 3332)	0.0844754682576354
  :	:
  (49581, 4890)	0.10682334916138103
  (49581, 1542)	0.17584072573791829
  (49581, 4493)	0.09410069396961679
  (49581, 433)	0.11251655954741112
  (49581, 4276)	0.10905956327445408
  (49581, 1958)	0.0999074542943991
  (49581, 554)	0.08424218838425554
  (49581, 2187)	0.14180348667063264
  (49581, 2217)	0.09535602544797335
  (49581, 4346)	0.17508214877875983
  (49581, 4629)	0.1157123083349983
  (49581, 3646)	0.087334023293812
  (49581, 4734)	0.12354122837064464
  (49581, 1977)	0.1279546327938257
  (49581, 526)	0.1247934452922504
  (49581, 2622)	0.17341357547872566
  (49581, 4457)	0.16002233459530202
  (49581, 2174)	0.18983797727912208
  (49581, 4032)	0.20100044911463438
  (49581, 341)	0.14784964476913964
  (49581, 2696)	0.1740080872946952
  (49581, 438)	0.13323526536564564
  (49581, 4980)	0.15095820717373318
  (49581, 1764)	0.15815315432712562
  (49581, 3489)	0.1519741559925848